// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuqfnvKcOOzTJZW1TfAGj0TMDJbvtZpNs',
    appId: '1:247168341628:web:7518cb7c2ee63567a91bf9',
    messagingSenderId: '247168341628',
    projectId: 'advanced-store-4419e',
    authDomain: 'advanced-store-4419e.firebaseapp.com',
    storageBucket: 'advanced-store-4419e.firebasestorage.app',
    measurementId: 'G-CCS45KFWF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq4X54GS5Q0rruqAb0Ui3A64Rx-wroCVI',
    appId: '1:247168341628:android:fe8999a3a7bfbfc4a91bf9',
    messagingSenderId: '247168341628',
    projectId: 'advanced-store-4419e',
    storageBucket: 'advanced-store-4419e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOz6jeeMBj_XJ7ut8BCukmHXC6X3gz6xE',
    appId: '1:247168341628:ios:a7f674c8a1927860a91bf9',
    messagingSenderId: '247168341628',
    projectId: 'advanced-store-4419e',
    storageBucket: 'advanced-store-4419e.firebasestorage.app',
    iosBundleId: 'com.example.advancedStoreProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOz6jeeMBj_XJ7ut8BCukmHXC6X3gz6xE',
    appId: '1:247168341628:ios:a7f674c8a1927860a91bf9',
    messagingSenderId: '247168341628',
    projectId: 'advanced-store-4419e',
    storageBucket: 'advanced-store-4419e.firebasestorage.app',
    iosBundleId: 'com.example.advancedStoreProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuqfnvKcOOzTJZW1TfAGj0TMDJbvtZpNs',
    appId: '1:247168341628:web:1d2f49b18104a7caa91bf9',
    messagingSenderId: '247168341628',
    projectId: 'advanced-store-4419e',
    authDomain: 'advanced-store-4419e.firebaseapp.com',
    storageBucket: 'advanced-store-4419e.firebasestorage.app',
    measurementId: 'G-5NQDMR3EQG',
  );
}
